Delta service
JesseLabruyere/Delta_LoRaWAN pull request #20
Opened 2016-09-23 10:42 UTC by JesseLabruyere

2016-09-23 12:23 UTC, LeanderM commented on app/Http/Controllers/Devices/DeviceController.php
> +        return $this->response->created();
This return always says the store-ing failed, even if it did not. if/else?

2016-09-23 12:44 UTC, LeanderM commented on app/Http/Requests/Devices/DeviceStoreRequest.php
> +            'name' => 'required|max:255',
Om data te besparen kortere namen?

2016-09-23 12:45 UTC, LeanderM commented on app/Http/Requests/Devices/DeviceUpdateRequest.php
> +        return true;
Most epic authorization ever :p

2016-09-23 12:47 UTC, LeanderM commented on app/User.php
> +        return $this->hasMany('Delta\DeltaService\Roles\RoleModel', 'users_id');
beide zijn koppeltabellen, maar de koppelingen zelf verschillen?

2016-09-23 12:48 UTC, LeanderM commented on config/delta_service.php
> +    'connection' => [
waarom zit dit niet in env?

2016-09-23 12:50 UTC, LeanderM requested changes

2016-09-24 19:39 UTC, markdingemanse commented on app/Http/Controllers/Devices/DeviceController.php
> +        return $this->response->created();
hier kijken we maandag naar.

2016-09-24 19:40 UTC, markdingemanse commented on app/Http/Requests/Devices/DeviceStoreRequest.php
> +            'name' => 'required|max:255',
klopt voornamelijk relevant voor de measurements requests. Graag de andere requests leesbaar houden : P

2016-09-24 19:41 UTC, markdingemanse commented on app/Http/Requests/Devices/DeviceUpdateRequest.php
> +        return true;
Volgens mij een verplichting vanuit dingo zal maandag effe checken.

2016-09-24 19:42 UTC, markdingemanse commented on app/User.php
> +        return $this->hasMany('Delta\DeltaService\Roles\RoleModel', 'users_id');
hier kijken we maandag naar.

2016-09-24 19:44 UTC, markdingemanse commented on config/delta_service.php
> +    'connection' => [
omdat de package anders niet gepublished kan worden. De uiteindelijke concrete config waarden staan nogsteeds in .env check de config map daar staat de gepublishte config file op basis van deze abstractie

2016-09-26 07:45 UTC, markdingemanse commented on app/Http/Controllers/Devices/DeviceController.php
> +        return $this->response->created();
wordt later een job definitie die gedischarged kan worden vanuit de controller op een multhi threaded manier voor nu alleen repository methode fixen array in object maken en die createn en tru returnen

2016-09-26 07:46 UTC, LeanderM commented on app/Http/Requests/Devices/DeviceUpdateRequest.php
> +        return true;
zet dit anders ff in de comments, dan is het wat logischer voor de casual observer

2016-09-26 07:47 UTC, markdingemanse commented on app/User.php
> +        return $this->hasMany('Delta\DeltaService\Roles\RoleModel', 'users_id');
moet beide belongtomany zijn

2016-09-26 08:14 UTC, LeanderM approved these changes

2016-09-26 08:16 UTC, merged